### ISSUE TITLE
Brick improvements

### ISSUE THREAD

**Issue by corradio** [tmrowco/brick#3]
- [x] add build dependencies (https://github.com/tmrowco/brick/issues/14)
- [x] support a case where docker-compose tests are used (#509)
- [x] support gcloud deploys (https://github.com/tmrowco/tmrowapp/pull/508)
- [ ] ~support integrations (docker-compose) tests (https://github.com/tmrowco/electricitymap/issues/1529)~
- [x] support deploy case
- [x] cache builds depending on branch
- [x] cache/mount previous node_modules / yarn cache (https://github.com/tmrowco/brick/issues/17)
- [x] support `watch` case
- [ ] allow concurrent builds (by having a different .brickdockerfile) (https://github.com/tmrowco/brick/issues/new)
- [ ] ~support a case where Dockerfile are used~
- [ ] remove `name` and only use tags / folder names? (https://github.com/tmrowco/brick/issues/59)
